### PR TITLE
Add Travis configuration

### PR DESCRIPTION
**Pull request by orien**
Hopefully this'll get the build green

### CODE REVIEW

**Comment by orien** [comment]
It doesn't quite get to green. But at least now there's output identifying the linting problems.

**Comment by orien** [comment]
De-linted the problems identified by the build.

**Comment by jacobbednarz** [comment]
Thanks for the effort on this one, I really appreciate it! Other modules are using [cardboard](https://github.com/boxen/cardboard) instead of hand rolled configurations like this. Would you be able to use that instead? [boxen/puppet-boxen](https://github.com/boxen/puppet-boxen) is a pretty solid example of this.

**Comment by orien** [comment]
@jacobbednarz This build is already using Cardboard. I've updated it to the latest version.

**Comment by jacobbednarz** [comment]
Thanks! 💯

**Pull request merged**
